### ISSUE TITLE
Create a new cli script to execute a zeppelin notebook

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/python-zeppelin#13]
Among other things, this script will:

- [x] run a notebook against a zeppelin instance (probably using the zeppelin http api)
- [x] detect errors in the execution and eventually print those errors to stderr (using the markdown converter)
- [x] fetch the notebook executed (i.e. with the results filled) and save it to $output_path
- [x] return an appropriate error code

**Comment by comloo** [comment]
#18
